// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBES5bagY1P6uLMbdE9s2zwkv8w13NICCg',
    appId: '1:1079921888354:web:93fab7e927bb09ee6b553b',
    messagingSenderId: '1079921888354',
    projectId: 'spotifycloneha',
    authDomain: 'spotifycloneha.firebaseapp.com',
    storageBucket: 'spotifycloneha.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv_pk7nQd5eVzsqXA5ksjWHjYTX0sYkL4',
    appId: '1:1079921888354:android:b29de0ed7609d7136b553b',
    messagingSenderId: '1079921888354',
    projectId: 'spotifycloneha',
    storageBucket: 'spotifycloneha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyBItbcBQWVD_DqomhEacxpM5VBvvFrGw',
    appId: '1:1079921888354:ios:4ecc471ba1c521036b553b',
    messagingSenderId: '1079921888354',
    projectId: 'spotifycloneha',
    storageBucket: 'spotifycloneha.firebasestorage.app',
    iosBundleId: 'com.example.clonespotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyBItbcBQWVD_DqomhEacxpM5VBvvFrGw',
    appId: '1:1079921888354:ios:4ecc471ba1c521036b553b',
    messagingSenderId: '1079921888354',
    projectId: 'spotifycloneha',
    storageBucket: 'spotifycloneha.firebasestorage.app',
    iosBundleId: 'com.example.clonespotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBES5bagY1P6uLMbdE9s2zwkv8w13NICCg',
    appId: '1:1079921888354:web:4f1453e3ea80a85a6b553b',
    messagingSenderId: '1079921888354',
    projectId: 'spotifycloneha',
    authDomain: 'spotifycloneha.firebaseapp.com',
    storageBucket: 'spotifycloneha.firebasestorage.app',
  );
}
